[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solidity_version = '0.8.22'
evm_version = 'shanghai'
via_ir = true
fs_permissions = [{ access = "read-write", path = "./" },]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
